# Generated by Django 6.0.2 on 2026-02-25 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_exam_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
